Update install-catbots

diff --git a/install-catbots b/install-catbots
--- a/install-catbots
+++ b/install-catbots
@@ -6,16 +6,34 @@ if [ $EUID == 0 ]; then
     exit
 fi
 
-if ! [ -e "/opt/cathook/" ]; then
-    echo "Please install Cathook on your main TF2, first."
-    echo "https://github.com/cyrexlinuz/cathook"
-    exit
-fi
-
 # Idiot proof this shit
 if ! [ -d ".git" ]; then
     echo "You must clone the repo instead of downloading it."
     exit
+fi
+
+if ! [ -e "/opt/cathook/" ]; then
+    echo "Previous Cathook installation not found! Let's install it..."
+    cd; git clone https://github.com/cyrexlinuz/cathook
+    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+    git fetch --unshallow
+    git submodule foreach --recursive 'git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"'
+    git submodule foreach --recursive 'git fetch --unshallow'
+    
+    # config setup
+    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+    configfile="$DIR/updater-preferences"
+    . config.shlib
+    cfg_write $configfile update_channel developer
+    cfg_write $configfile autoupdater false
+    ./install-all
+    
+    if ! [ -e "/opt/cathook/" ]; then
+        echo "Failed to install Cyrex's Cathook fork! You have to do that manually. You can contact me about it."
+        exit
+    fi
+    
+    echo "Cathook installation succeded."
 fi
 
 if [ -f /usr/bin/apt-get ]; then
