Update start

diff --git a/start b/start
--- a/start
+++ b/start
@@ -10,6 +10,11 @@ if ! [ -d "./user_instances" ]; then
 	exit
 fi
 
+if ! [ -d "./accounts.txt" ]; then
+	echo "accounts.txt is missing. Are you aware of this? Perhaps you forgot creating Steam accounts from https://accgen.cathook.club"
+	exit
+fi
+
 sudo mkdir -p /opt/steamapps
 mountpoint -q /opt/steamapps || sudo mount --bind ~/.steam/steam/steamapps/ /opt/steamapps
 
